FROM ubuntu:24.04 AS base


ENV PYMEMDYN=/root/pymemdyn \
    DEBIAN_FRONTEND=noninteractive


# Update, Install Python3 and dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl unzip python3 python3-pip python3-numpy && \
    apt clean && \
    rm -rf /var/apt/lists


# Install biopython from pip
RUN pip install --no-cache --break-system-packages biopython rdkit

# Install gromacs from local directory, and extract inside the container
COPY ./gromacs.tar.gz /tmp/gromacs.tar.gz
RUN tar xzvf /tmp/gromacs.tar.gz -C / && \
    rm /tmp/gromacs.tar.gz


# Install PyMemDyn
RUN cd /root && \
    curl -LO https://github.com/GPCR-ModSim/pymemdyn/archive/refs/heads/main.zip && \
    unzip main.zip && \
    mv pymemdyn-main pymemdyn && \
    rm main.zip


# Add pymemdyn executable to path by soft-linking
RUN ln -s /root/pymemdyn/pymemdyn /usr/local/bin/pymemdyn  

 
ENTRYPOINT [ "/usr/local/bin/pymemdyn" ]
